-- Editor chrome, legacy syntax groups, diagnostics and core LSP groups.
-- Values follow SPEC.md section 5 (IntelliJ attribute table).
return function(c, opts)
  local ui, syn, d = c.ui, c.syn, c.diag

  -- stylua: ignore
  return {
    -- editor
    Normal          = { fg = ui.fg, bg = ui.bg },
    NormalNC        = { fg = ui.fg, bg = ui.bg_nc },
    NormalFloat     = { fg = ui.fg, bg = ui.bg_float },
    FloatBorder     = { fg = ui.fg_border, bg = ui.bg_float },
    FloatTitle      = { fg = ui.fg_title, bg = ui.bg_float },
    FloatFooter     = { fg = ui.fg_dim, bg = ui.bg_float },
    NormalSB        = { fg = ui.fg, bg = ui.bg_gutter },
    Cursor          = { fg = ui.cursor_fg, bg = ui.cursor_bg },
    lCursor         = "Cursor",
    CursorIM        = "Cursor",
    TermCursor      = "Cursor",
    CursorLine      = { bg = ui.bg_cursorline },
    CursorColumn    = { bg = ui.bg_cursorline },
    ColorColumn     = { bg = ui.bg_gutter },
    CursorLineNr    = { fg = ui.fg_line_nr_cur, bg = ui.bg_cursorline },
    LineNr          = { fg = ui.fg_line_nr, bg = ui.bg_gutter },
    LineNrAbove     = "LineNr",
    LineNrBelow     = "LineNr",
    SignColumn      = { fg = ui.fg_line_nr, bg = ui.bg_gutter },
    CursorLineSign  = { bg = ui.bg_cursorline },
    FoldColumn      = { fg = ui.bg_sel, bg = ui.bg_gutter },
    CursorLineFold  = { fg = ui.bg_sel, bg = ui.bg_cursorline },
    Folded          = { fg = ui.fg_folded, bg = ui.bg_folded },
    Conceal         = { fg = ui.fg_dim },
    Directory       = { fg = ui.fg_directory },
    EndOfBuffer     = { fg = ui.bg },
    NonText         = { fg = ui.fg_nontext },
    Whitespace      = { fg = ui.fg_whitespace },
    SpecialKey      = { fg = ui.fg_nontext },
    VertSplit       = { fg = ui.fg_separator, bg = ui.bg },
    WinSeparator    = { fg = ui.fg_separator, bg = ui.bg },
    WinBar          = { fg = ui.fg, bg = ui.bg },
    WinBarNC        = { fg = ui.fg_dim, bg = ui.bg_nc },
    Visual          = { bg = ui.bg_visual },
    VisualNOS       = { bg = ui.bg_visual },
    Search          = { bg = ui.bg_search },
    CurSearch       = { bg = ui.bg_cursearch, underline = true, sp = ui.sp_cursearch },
    IncSearch       = "CurSearch",
    Substitute      = { fg = ui.fg, bg = ui.bg_ref_write },
    MatchParen      = { bg = ui.bg_match, bold = true },
    QuickFixLine    = { bg = ui.bg_visual },
    Title           = { fg = ui.fg_title, bold = true },
    Underlined      = { fg = ui.fg_link, underline = true },
    Bold            = { bold = true },
    Italic          = {}, -- never italic
    BoldItalic      = { bold = true },
    ErrorMsg        = { fg = d.error },
    WarningMsg      = { fg = d.warn },
    MoreMsg         = { fg = d.ok },
    Question        = { fg = d.ok },
    ModeMsg         = { fg = ui.fg_dim },
    MsgArea         = { fg = ui.fg },
    MsgSeparator    = { fg = ui.fg_separator, bg = ui.bg_gutter },
    WildMenu        = { bg = ui.bg_pmenu_sel },
    ComplMatchIns   = { fg = ui.fg_dim },

    -- popup menu
    Pmenu           = { fg = ui.fg, bg = ui.bg_pmenu },
    PmenuSel        = { bg = ui.bg_pmenu_sel },
    PmenuKind       = { fg = ui.fg_dim, bg = ui.bg_pmenu },
    PmenuKindSel    = { fg = ui.fg_dim, bg = ui.bg_pmenu_sel },
    PmenuExtra      = { fg = ui.fg_dim, bg = ui.bg_pmenu },
    PmenuExtraSel   = { fg = ui.fg_dim, bg = ui.bg_pmenu_sel },
    PmenuMatch      = { fg = syn.keyword, bg = ui.bg_pmenu },
    PmenuMatchSel   = { fg = syn.keyword, bg = ui.bg_pmenu_sel },
    PmenuSbar       = { bg = ui.bg_gutter },
    PmenuThumb      = { bg = ui.fg_border },

    -- status, tabs
    StatusLine      = { fg = ui.fg, bg = ui.bg_statusline },
    StatusLineNC    = { fg = ui.fg_dim, bg = ui.bg_statusline },
    StatusLineTerm  = "StatusLine",
    StatusLineTermNC = "StatusLineNC",
    TabLine         = { fg = ui.fg_dim, bg = ui.bg_gutter },
    TabLineFill     = { bg = ui.bg_dark },
    TabLineSel      = { fg = ui.fg, bg = ui.bg },

    -- spelling: IntelliJ TYPO is a text-colored undercurl
    SpellBad        = { undercurl = true, sp = ui.sp_spell },
    SpellCap        = { undercurl = true, sp = d.info },
    SpellLocal      = { undercurl = true, sp = d.hint },
    SpellRare       = { undercurl = true, sp = d.hint },

    -- diff mode
    DiffAdd         = { bg = c.diff.add },
    DiffChange      = { bg = c.diff.change },
    DiffDelete      = { bg = c.diff.delete },
    DiffText        = { bg = c.diff.text },
    Added           = { fg = c.git.add },
    Changed         = { fg = c.git.change_fg },
    Removed         = { fg = c.git.delete },
    diffAdded       = "Added",
    diffRemoved     = "Removed",
    diffChanged     = "Changed",
    diffOldFile     = { fg = c.git.delete },
    diffNewFile     = { fg = c.git.add },
    diffFile        = { fg = syn.type },
    diffLine        = { fg = ui.fg_dim },
    diffIndexLine   = { fg = ui.fg_dim },

    -- legacy syntax (treesitter captures link here)
    Comment         = { fg = syn.comment },
    SpecialComment  = { fg = syn.todo },
    Todo            = { fg = syn.todo },
    Constant        = { fg = syn.constant, bold = true },
    String          = { fg = syn.string },
    Character       = { fg = syn.string },
    Number          = { fg = syn.number },
    Float           = { fg = syn.number },
    Boolean         = "Keyword",
    Identifier      = { fg = syn.fg },
    Function        = { fg = syn.fg, bold = true },
    Statement       = "Keyword",
    Conditional     = "Keyword",
    Repeat          = "Keyword",
    Label           = { fg = syn.fg },
    Operator        = { fg = syn.operator },
    Keyword         = { fg = syn.keyword, bold = true },
    Exception       = "Keyword",
    PreProc         = "Keyword",
    Include         = "Keyword",
    Define          = "Keyword",
    Macro           = "Keyword",
    PreCondit       = "Keyword",
    Type            = { fg = syn.type },
    StorageClass    = "Keyword",
    Structure       = "Type",
    Typedef         = "Type",
    Special         = { fg = syn.special },
    SpecialChar     = { fg = syn.escape, bold = true },
    Tag             = { fg = syn.tag },
    Delimiter       = { fg = syn.delimiter },
    Debug           = { fg = ui.fg_dim },
    Error           = { fg = d.error },

    -- lsp
    LspReferenceText            = { underline = true, sp = ui.sp_ref },
    LspReferenceRead            = { underline = true, sp = ui.sp_ref },
    LspReferenceWrite           = { underline = true, sp = ui.sp_ref },
    LspReferenceTarget          = { underline = true, sp = ui.sp_ref },
    LspSignatureActiveParameter = { fg = syn.keyword, bold = true },
    LspCodeLens                 = { fg = ui.fg_faint },
    LspCodeLensSeparator        = { fg = ui.fg_faint },
    LspInlayHint                = { fg = ui.fg_inlay, bg = ui.bg_hint },
    LspInfoBorder               = "FloatBorder",

    -- diagnostics: undercurl inline, dimmed virtual text, no line fills
    DiagnosticError           = { fg = d.error },
    DiagnosticWarn            = { fg = d.warn },
    DiagnosticInfo            = { fg = d.info },
    DiagnosticHint            = { fg = d.hint },
    DiagnosticOk              = { fg = d.ok },
    DiagnosticVirtualTextError = { fg = d.vt_error },
    DiagnosticVirtualTextWarn  = { fg = d.vt_warn },
    DiagnosticVirtualTextInfo  = { fg = d.vt_info },
    DiagnosticVirtualTextHint  = { fg = d.vt_hint },
    DiagnosticVirtualTextOk    = { fg = d.vt_hint },
    DiagnosticVirtualLinesError = "DiagnosticVirtualTextError",
    DiagnosticVirtualLinesWarn  = "DiagnosticVirtualTextWarn",
    DiagnosticVirtualLinesInfo  = "DiagnosticVirtualTextInfo",
    DiagnosticVirtualLinesHint  = "DiagnosticVirtualTextHint",
    DiagnosticUnderlineError  = { undercurl = true, sp = d.sp_error },
    DiagnosticUnderlineWarn   = { undercurl = true, sp = d.sp_warn },
    DiagnosticUnderlineInfo   = { undercurl = true, sp = d.sp_info },
    DiagnosticUnderlineHint   = { undercurl = true, sp = d.sp_hint },
    DiagnosticUnderlineOk     = { undercurl = true, sp = d.sp_hint },
    DiagnosticUnnecessary     = { fg = d.unnecessary },
    DiagnosticDeprecated      = { strikethrough = true },
    DiagnosticSignError       = "DiagnosticError",
    DiagnosticSignWarn        = "DiagnosticWarn",
    DiagnosticSignInfo        = "DiagnosticInfo",
    DiagnosticSignHint        = "DiagnosticHint",
    DiagnosticFloatingError   = "DiagnosticError",
    DiagnosticFloatingWarn    = "DiagnosticWarn",
    DiagnosticFloatingInfo    = "DiagnosticInfo",
    DiagnosticFloatingHint    = "DiagnosticHint",

    -- misc builtin
    healthError     = { fg = d.error },
    healthSuccess   = { fg = d.ok },
    healthWarning   = { fg = d.warn },
    qfFileName      = { fg = syn.type },
    qfLineNr        = { fg = ui.fg_faint },
    debugPC         = { bg = ui.bg_sel },
    debugBreakpoint = { fg = d.error, bg = ui.bg_gutter },
    helpCommand     = { fg = syn.doc_markup },
    helpExample     = { fg = syn.doc_markup },
    helpHeader      = "Title",
    helpHyperTextJump = { fg = ui.fg_link, underline = true },
    helpSectionDelim = { fg = ui.fg_faint },
    Terminal        = { fg = ui.fg, bg = ui.bg_dark },

    -- indent guides: other plugins link here (blink.indent in the owner config)
    IblIndent       = { fg = ui.fg_indent },
    IblWhitespace   = { fg = ui.fg_whitespace },
    IblScope        = { fg = ui.fg_indent_scope },
  }
end
