return function(c, opts)
  local ui, syn, d = c.ui, c.syn, c.diag
  return {
    CodeCompanionChatHeader = { fg = syn.type, bold = true },
    CodeCompanionChatSeparator = { fg = ui.fg_border },
    CodeCompanionChatFold = { fg = ui.fg_dim },
    CodeCompanionChatSubtext = { fg = ui.fg_dim },
    CodeCompanionChatTokens = { fg = ui.fg_dim },
    CodeCompanionChatInfo = "DiagnosticInfo",
    CodeCompanionChatWarn = "DiagnosticWarn",
    CodeCompanionChatError = "DiagnosticError",
    CodeCompanionChatEditorContext = { fg = syn.interface },
    CodeCompanionChatContext = { fg = syn.interface },
    CodeCompanionChatContextIcon = { fg = syn.interface },
    CodeCompanionChatTool = { fg = syn.keyword },
    CodeCompanionChatToolGroup = { fg = syn.type },
    CodeCompanionChatToolText = { fg = ui.fg_dim },
    CodeCompanionChatToolPending = { fg = d.warn },
    CodeCompanionChatToolPendingIcon = { fg = d.warn },
    CodeCompanionChatToolInProgress = { fg = d.info },
    CodeCompanionChatToolInProgressIcon = { fg = d.info },
    CodeCompanionChatToolSuccess = { fg = syn.todo },
    CodeCompanionChatToolSuccessIcon = { fg = syn.todo },
    CodeCompanionChatToolFailure = { fg = d.error },
    CodeCompanionChatToolFailureIcon = { fg = d.error },
    CodeCompanionDiffAdd = "DiffAdd",
    CodeCompanionDiffDelete = "DiffDelete",
    CodeCompanionDiffText = "DiffText",
    CodeCompanionDiffTextDelete = "DiffDelete",
    CodeCompanionDiffBanner = { fg = syn.type },
    CodeCompanionDiffBannerInline = { fg = ui.fg_faint },
    CodeCompanionCLIPath = "Directory",
    CodeCompanionCodeReviewAdded = "Added",
    CodeCompanionCodeReviewRemoved = "Removed",
    CodeCompanionCodeReviewComment = "Comment",
    CodeCompanionCodeReviewHeader = { fg = syn.type, bold = true },
    CodeCompanionCodeReviewSent = { fg = ui.fg_faint },
    CodeCompanionCodeReviewPath = "Directory",
    CodeCompanionVirtualText = { fg = ui.fg_faint },
  }
end
