return function(c, opts)
  local g = c.git
  return {
    GitSignsAdd = { fg = g.add },
    GitSignsChange = { fg = g.change },
    GitSignsDelete = { fg = g.delete },
    GitSignsChangedelete = { fg = g.change },
    GitSignsTopdelete = { fg = g.delete },
    GitSignsUntracked = { fg = g.add },
    GitSignsAddNr = { fg = g.add },
    GitSignsChangeNr = { fg = g.change },
    GitSignsDeleteNr = { fg = g.delete },
    GitSignsAddLn = { bg = c.diff.add },
    GitSignsChangeLn = { bg = c.diff.change },
    GitSignsDeleteLn = { bg = c.diff.delete },
    GitSignsAddInline = { bg = c.diff.add },
    GitSignsChangeInline = { bg = c.diff.text },
    GitSignsDeleteInline = { bg = c.diff.delete },
    GitSignsAddPreview = { bg = c.diff.add },
    GitSignsDeletePreview = { bg = c.diff.delete },
    GitSignsCurrentLineBlame = { fg = c.ui.fg_faint },
    GitSignsStagedAdd = { fg = c.palette.comment },
    GitSignsStagedChange = { fg = c.palette.change },
    GitSignsStagedDelete = { fg = c.palette.error_bg },
    GitSignsChangedeleteNr = "GitSignsChangeNr",
    GitSignsTopdeleteNr = "GitSignsDeleteNr",
    GitSignsUntrackedNr = "GitSignsAddNr",
    GitSignsChangedeleteLn = "GitSignsChangeLn",
    GitSignsUntrackedLn = "GitSignsAddLn",
    GitSignsAddCul = "GitSignsAdd",
    GitSignsChangeCul = "GitSignsChange",
    GitSignsDeleteCul = "GitSignsDelete",
    GitSignsChangedeleteCul = "GitSignsChangedelete",
    GitSignsTopdeleteCul = "GitSignsTopdelete",
    GitSignsUntrackedCul = "GitSignsUntracked",
    GitSignsStagedChangedelete = "GitSignsStagedChange",
    GitSignsStagedTopdelete = "GitSignsStagedDelete",
    GitSignsStagedUntracked = "GitSignsStagedAdd",
    GitSignsStagedAddNr = "GitSignsStagedAdd",
    GitSignsStagedChangeNr = "GitSignsStagedChange",
    GitSignsStagedDeleteNr = "GitSignsStagedDelete",
    GitSignsStagedChangedeleteNr = "GitSignsStagedChangedelete",
    GitSignsStagedTopdeleteNr = "GitSignsStagedTopdelete",
    GitSignsStagedUntrackedNr = "GitSignsStagedUntracked",
    GitSignsStagedAddLn = "GitSignsAddLn",
    GitSignsStagedChangeLn = "GitSignsChangeLn",
    GitSignsStagedChangedeleteLn = "GitSignsChangedeleteLn",
    GitSignsStagedUntrackedLn = "GitSignsUntrackedLn",
    GitSignsStagedAddCul = "GitSignsStagedAdd",
    GitSignsStagedChangeCul = "GitSignsStagedChange",
    GitSignsStagedDeleteCul = "GitSignsStagedDelete",
    GitSignsStagedChangedeleteCul = "GitSignsStagedChangedelete",
    GitSignsStagedTopdeleteCul = "GitSignsStagedTopdelete",
    GitSignsStagedUntrackedCul = "GitSignsStagedUntracked",
    GitSignsDiffStaged = { fg = c.ui.fg_dim },
    GitSignsNoEOLPreview = { fg = c.ui.fg_faint },
    GitSignsAddLnInline = "GitSignsAddInline",
    GitSignsChangeLnInline = "GitSignsChangeInline",
    GitSignsDeleteLnInline = "GitSignsDeleteInline",
    GitSignsDeleteVirtLn = "GitSignsDeletePreview",
    GitSignsDeleteVirtLnInLine = "GitSignsDeleteLnInline",
    GitSignsVirtLnum = "GitSignsDeleteVirtLn",
  }
end
