return function(c, opts)
  local ui, syn, d, g = c.ui, c.syn, c.diag, c.git
  return {
    NvimTreeNormal = { fg = ui.fg, bg = ui.bg_gutter },
    NvimTreeNormalNC = "NvimTreeNormal",
    NvimTreeNormalFloat = "NormalFloat",
    NvimTreeWinSeparator = { fg = ui.fg_separator, bg = ui.bg_gutter },
    NvimTreeEndOfBuffer = { fg = ui.bg_gutter },
    NvimTreeCursorLine = { bg = ui.bg_sel },
    NvimTreeRootFolder = { fg = ui.fg_directory, bold = true },
    NvimTreeFolderName = { fg = ui.fg_directory },
    NvimTreeFolderIcon = { fg = ui.fg_directory },
    NvimTreeEmptyFolderName = { fg = ui.fg_directory },
    NvimTreeOpenedFolderName = { fg = ui.fg_directory },
    NvimTreeOpenedFolderIcon = { fg = ui.fg_directory },
    NvimTreeIndentMarker = { fg = ui.fg_faint },
    NvimTreeSymlink = { fg = syn.interface },
    NvimTreeExecFile = { fg = d.ok },
    NvimTreeOpenedFile = { bold = true },
    NvimTreeSpecialFile = { fg = syn.keyword },
    NvimTreeImageFile = { fg = ui.fg },
    NvimTreeWindowPicker = { fg = ui.bg, bg = syn.keyword, bold = true },
    NvimTreeGitDirty = { fg = g.change_fg },
    NvimTreeGitStaged = { fg = g.add },
    NvimTreeGitMerge = { fg = g.conflict },
    NvimTreeGitRenamed = { fg = g.change_fg },
    NvimTreeGitNew = { fg = g.add },
    NvimTreeGitDeleted = { fg = g.delete },
    NvimTreeGitIgnored = { fg = ui.fg_faint },
    NvimTreeLspDiagnosticsError = { fg = d.error },
    NvimTreeLspDiagnosticsWarning = { fg = d.warn },
    NvimTreeLspDiagnosticsInformation = { fg = d.info },
    NvimTreeLspDiagnosticsHint = { fg = d.hint },
  }
end
